#ifndef CONFIG_H_
#define CONFIG_H_

const double CONFIG_CURRENT_VOLTAGE_FACTOR_CHANNEL_A = 6072.0;
const double CONFIG_CURRENT_VOLTAGE_FACTOR_CHANNEL_B = 6048.0;
const double CONFIG_VOLTAGE_OFFSET_CHANNEL_A = 0.0084;
const double CONFIG_VOLTAGE_OFFSET_CHANNEL_B = 0.0014;

const double CONFIG_TRIGGER_LEVEL_CURRENT = 200.0; // A

const float CONFIG_REARM_COOLDOWN_SECONDS = 90.0f;

const float CONFIG_MAX_VOLTAGE = 2000.0f;
const float CONFIG_MIN_VOLTAGE = 0.0f;

const float CONFIG_TARGET_CHARGING_CURRENT = 200.0f; // mA


#endif // CONFIG_H_
